### ISSUE TITLE
New logo design

### ISSUE THREAD

**Issue by abhishalya** [JuliaStrings/StringEncodings.jl#34]
Part of [Google Code-in task](https://codein.withgoogle.com/dashboard/task-instances/4713510597033984/).

![image](https://user-images.githubusercontent.com/34682737/71256936-5649e900-2358-11ea-97a0-5c5c2dee7752.png)

[LICENSE.txt](https://github.com/JuliaStrings/StringEncodings.jl/files/3988393/LICENSE.txt)

**Comment by logankilpatrick** [comment]
@StefanKarpinski @ViralBShah New logo for the Julia String's Org! Nice work @abhishalya

**Comment by ViralBShah** [comment]
Nice!

**Comment by logankilpatrick** [comment]
Feel free to close if you don't want to use the Logo or after it has been uploaded as the org logo.

**Comment by ViralBShah** [comment]
I've made it the org logo.

**Comment by ViralBShah** [comment]
@abhishalya Can you also upload an svg version here?

**Comment by abhishalya** [comment]
@ViralBShah I can't attach svg files here, seems like Github doesn't support it.

Its there on the code-in site though.

**Comment by ViralBShah** [comment]
Thanks. Can you post a URL to the code-in site?

**Comment by logankilpatrick** [comment]
https://codein.withgoogle.com/dashboard/task-instances/4713510597033984/

**Comment by ViralBShah** [comment]
Uploaded svg logo as a gist: https://gist.github.com/ViralBShah/dfb5e84e31e74334d38934918fec127d
