### ISSUE TITLE
Use BinaryBuilder

### ISSUE THREAD

**Issue by ViralBShah** [JuliaStrings/StringEncodings.jl#36]
Since libiconv is already available in BB, it should be straightforward to use it.

**Comment by nalimilan** [comment]
It might be a be trickier than it sounds, as we currently don't install libiconv where it's already present (most Linux systems and macOS). I guess we could install GNU libiconv anyway if there's no way around it.

**Comment by stevengj** [comment]
I would just install it everywhere; disk space is cheap.

Optionally, you could choose to *use* the system `libiconv` on Linux and macOS instead of the BinaryBuilder package.  On the other hand, using the Julia one everywhere has the advantage that the results are more reproducible across platfoms.

**Comment by nalimilan** [comment]
Yes that's the conclusion I arrived to as well. Even if it sounds too bad to install something when it's already there, libiconv is quite small.
