### ISSUE TITLE
[Question] is there support for "utf-8-sig" ? 

### ISSUE THREAD

**Issue by 4aHxKzD** [JuliaStrings/StringEncodings.jl#45]
I'm trying to read a file that if the encoding selected is enc"UTF-8" it starts with "\ufeff". In Python the solution was to use "utf-8-sig" .

**Comment by nalimilan** [comment]
AFAICT iconv doesn't support that. I guess we could special-case that encoding and remove the `'\ufeff'` byte-order mark if it's present, but that wouldn't be super pretty. It will be simpler for you to just skip the first character (then you don't even need StringEncodings).

**Comment by 4aHxKzD** [comment]
> It will be simpler for you to just skip the first character (then you don't even need StringEncodings).

That's what I ended up doing, thanks!
