### ISSUE TITLE
Empty output from encode()

### ISSUE THREAD

**Issue by tomyun** [JuliaStrings/StringEncodings.jl#49]
```julia
julia> encode("ク", "shift_jisx0213")
UInt8[]
```

This should have provided the same result as "sjis" encoding.

```julia
julia> encode("ク", "sjis")
2-element Vector{UInt8}:
 0x83
 0x4e
```

**Comment by nalimilan** [comment]
Thanks for the report. I suspect this is an issue in GNU libiconv, as it doesn't seem to write anything to the output buffer. Would you file an issue in their bug tracker?

**Comment by tomyun** [comment]
While I don't quite understand iconv behavior either (i.e. compared to "sjis" encoding which just works), it's also clearly stated that the output buffer should be explicitly flushed out by caller to prevent partial results like this go missing.

> In each series of calls to iconv(), the last should be one with inbuf or *inbuf equal to NULL, in order to flush out any partially converted input.

With that, it seems like `iconv_reset!()` should be called somewhere like in `flush()` for StringEncodings.jl to properly handle this kind of case.

Related discussion in other language can be found here if needed: racket/racket#3876

**Comment by nalimilan** [comment]
Woops, indeed there was a missing operation after closing the stream. I'm not sure why the existing tests didn't catch this, given that I've checked that they cover a case where final bytes are written in a stateful encoding. Anyway, see https://github.com/JuliaStrings/StringEncodings.jl/pull/50.
